/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string
/**
 * Validates a license key by calling the provided license service endpoint.
 * Returns the raw JSON response from the license service.
 */
export declare function verifyLicenseKey(licenseKey: string, hardwareId: string, endpoint: string): Promise<unknown>
/**
 * Compatibility alias kept for older JS call sites.
 * Uses the current hardware id and the configured NATIVELY_LICENSE_API_URL.
 */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
export interface AudioDeviceInfo {
  id: string
  name: string
}
export declare function getInputDevices(): Array<AudioDeviceInfo>
export declare function getOutputDevices(): Array<AudioDeviceInfo>
export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
